<?php
// phpcs:disable WordPress.WP.I18n.TextDomainMismatch
/**
 * Partial template for displaying related Chiral posts.
 *
 * This template is used by Chiral_Connector_Display class (or JavaScript directly)
 * to render the list of related posts fetched from the Chiral Hub.
 *
 * Available Variables:
 * - $related_posts_data (array): An array of related post objects/arrays from the hub.
 *   Each item typically contains: 'title', 'url', 'excerpt' (optional), 'thumbnail_url' (optional).
 *
 * @package    Chiral_Connector
 * @subpackage Chiral_Connector/public/partials
 * @author     Your Name <email@example.com>
 */

if ( ! defined( 'WPINC' ) ) {
    die;
}

// Check if $related_posts_data is available and not empty.
// This template is intended to be included by a PHP function that sets this variable,
// or its structure is replicated by JavaScript that fetches data and builds the HTML.

// The following is a sample structure. JavaScript will likely build this dynamically.
// If this template were to be used by PHP (e.g., via AJAX returning full HTML), it would look like this:

/*
if ( ! empty( $related_posts_data ) ) :
?>
    <div class="chiral-related-posts-list">
        <h3><?php esc_html_e( 'Related Chiral Content', 'chiral-connector' ); ?></h3>
        <ul>
            <?php foreach ( $related_posts_data as $related_post ) : ?>
                <li>
                    <?php if ( ! empty( $related_post['thumbnail_url'] ) ) : ?>
                        <div class="related-post-thumbnail">
                            <a href="<?php echo esc_url( $related_post['url'] ); ?>" target="_blank" rel="noopener noreferrer">
                                <img src="<?php echo esc_url( $related_post['thumbnail_url'] ); ?>" alt="<?php echo esc_attr( $related_post['title'] ); ?>">
                            </a>
                        </div>
                    <?php endif; ?>
                    <div class="related-post-content">
                        <h4>
                            <a href="<?php echo esc_url( $related_post['url'] ); ?>" target="_blank" rel="noopener noreferrer">
                                <?php echo esc_html( $related_post['title'] ); ?>
                            </a>
                        </h4>
                        <?php if ( ! empty( $related_post['excerpt'] ) ) : ?>
                            <p><?php echo esc_html( $related_post['excerpt'] ); ?></p>
                        <?php endif; ?>
                         <small class="related-post-source"><?php printf( 
                             /* translators: %s: Domain name of the source website */
                             esc_html__( 'Source: %s', 'chiral-connector' ), 
                             esc_html( wp_parse_url($related_post['url'], PHP_URL_HOST) ) 
                         ); ?></small>
                    </div>
                </li>
            <?php endforeach; ?>
        </ul>
    </div>
<?php
else :
?>
    <p class="chiral-no-related-posts"><?php esc_html_e( 'No related Chiral data found at the moment.', 'chiral-connector' ); ?></p>
<?php
endif;
*/

// Since the documentation states that public JS fetches data and then renders,
// this PHP file primarily serves as a structural guide for the JS rendering logic.
// The actual content will be dynamically inserted by chiral-connector-public.js.
// So, this file might be empty or contain a very basic structure if not directly included by PHP for rendering.
// For now, let's leave it with comments explaining its role.

// If JavaScript is building the HTML, it will replicate a structure like the one commented out above.
// Example: It might look for a container like <div id="chiral-connector-related-posts"> and fill it.
?>
<!-- This is a template file for Chiral Connector related posts. -->
<!-- Content will be dynamically generated by JavaScript (public/assets/js/chiral-connector-public.js) -->
<!-- based on data fetched from the Chiral Hub. -->
<!-- The structure will typically include a list of items, each with a title, link, optional thumbnail, and excerpt. -->